config/routes.rb
DebtManager::Application.routes.draw do
  resources :debts
  resources :sessions

  root :to => 'debts#index'








  


end

app/models/debt.rb
class Debt < ActiveRecord::Base
  attr_accessible :name, :amount, :repaid, :user_id

  validates :name, :presence => true
  validates :amount, :repaid, :presence => true, :numericality => { :greater_than_or_equal_to => 0 } 

  def percentage
  	self.repaid / self.amount * 100
  end

  paginates_per 3

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  has_many :debts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

	def require_login
		unless session[:user_id]     #if session[:user_id] == nil
			flash[:error] = "Musite sa prihlasit"
			redirect_to new_session_url
		end
	end

	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  before_filter :require_login

  def index
  	# @debts = Debt.where(:user_id => current_user.id).page(params[:page])
    @debts = current_user.debts.page(params[:page])
  end

  def show
    # @debts = Debt.where(:user_id => current_user.id).page(params[:page])
    @debt = current_user.find params[:id]
  end

  def new
  	@debt = Debt.new
  end

  def create
  	@debt = Debt.new(params[:debt])
    @debt.user_id = current_user.id
  	if @debt.save
  		redirect_to debts_url
  	else
  		render :new
  	end
  end

  def edit
  	@debt = Debt.find params[:id]
  end

  def update
  	@debt = Debt.find params[:id]
  	 
  	if 
  		@debt.update_attributes params[:debt]
  		redirect_to debts_url
  	else 
  		render :edit
  	end
  end

  def destroy
    @debt = Debt.find params[:id]
    @debt.destroy
    redirect_to debts_url
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	

	def new
	end

	def create
		@user = User.where(:email => params[:email], :password => params[:password])
		if @user.any?
			session[:user_id] = @user.first.id

			flash[:notice] = "Boli ste prihlaseny"
			redirect_to root_path
		else
			flash[:error] = "Nespravne prihlasenie. Mozno len preklep, skuste znova."
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to new_session_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/debts/edit.html.erb
<%= form_for @debt do |f| %>

<table class="table_main">
	<tr>
		<td><%= f.label :name, "Nazov" %></td>
		<td><%= f.text_field :name %></td>
	</tr>
		<br />
	<tr>
		<td><%= f.label :amount, "Suma" %></td>
		<td><%= f.text_field :amount %></td>
		<br />
	</tr>
	<tr>	
		<td><%= f.label :repaid, "Splacam" %></td>
		<td><%= f.text_field :repaid %></td>
		<br />
	</tr>

</table><br />

<%= f.submit "Odoslat" %>
	
<% end %>

app/views/debts/index.html.erb
<table class="table_main">
	<tr>
		<th>Nazov</th>
		<th>Suma</th>
		<th>Splatene</th>
		<th>Akcia</th>
		<th class="bar_cell">Percento</th>
	</tr>
	<% @debts.each do |debt| %>
	<tr>
		<td><%= link_to debt.name, debt_path(debt) %></td>
		<td><%= number_to_currency debt.amount %></td>
		<td><%= number_to_currency debt.repaid %></td>
		<td><%= link_to "Upravit", edit_debt_path(debt) %> <%= link_to "Destroy", debt_path(debt), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
		<td class="bar_cell"><%= number_to_percentage debt.percentage, :precision => 2 %><%= content_tag :progress, :nil, :value => debt.repaid, :max => debt.amount %></td>
	</tr>
	<% end %>
</table><br />

<%= link_to "Novy dlh", new_debt_path %>

<%= paginate @debts %>


app/views/debts/new.html.erb
<%= form_for @debt do |f| %>

<table class="table_main">
	<tr>
		<td><%= f.label :name, "Nazov" %></td>
		<td><%= f.text_field :name %></td>
	</tr>
		<br />
	<tr>
		<td><%= f.label :amount, "Suma" %></td>
		<td><%= f.text_field :amount %></td>
		<br />
	</tr>
	<tr>	
		<td><%= f.label :repaid, "Splacam" %></td>
		<td><%= f.text_field :repaid %></td>
		<br />
	</tr>

</table><br />

<%= f.submit "Odoslat" %>
	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DebtManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to "Dlhy", root_path %></h1>
<p>
<% if current_user %>
	Vitaj <%= current_user.email %>
	<%= button_to 'Odhlasit', session_path(session), :method => :delete %>
<% else %>
	<%= link_to "Prihlasit sa", new_session_path %>
<% end %>
</p>


<div class="flash_notice"><%= flash[:notice] %></div>
<div class="flash_error"><%= flash[:error] %></div>
<hr/>

<%= yield %>

</body>
</html>